let routeConfig = {
    menuList: [
        {
            list: [
                {
                    menuId: 39,
                    parentId: 36,
                    name: "楼栋管理",
                    url: "test/default/index",
                    component: "@/views/base/components/test/default/index",
                    permit: "building:buildings:page",
                    type: 3,
                    icon: "zonghe",
                    oindex: 3,
                    createdBy: null,
                    updatedBy: null,
                    createdAt: null,
                    updatedAt: null,
                    pname: null,
                    list: null
                },   
            ]
        }
    ]
    
    
    
    
    
    
    
    
    
    
    
    
    // menuList: [
    //     {
    //         menuId: 36,
    //         parentId: 1,
    //         name: "项目管理",
    //         url: "",
    //         permit: "",
    //         type: 2,
    //         icon: "xiangmu",
    //         oindex: 89,
    //         createdBy: null,
    //         updatedBy: null,
    //         createdAt: null,
    //         updatedAt: null,
    //         pname: null,
    //         list: [
    //             {
    //                 menuId: 39,
    //                 parentId: 36,
    //                 name: "楼栋管理",
    //                 url: "test/default/index",
    //                 permit: "building:buildings:page",
    //                 type: 3,
    //                 icon: "zonghe",
    //                 oindex: 3,
    //                 createdBy: null,
    //                 updatedBy: null,
    //                 createdAt: null,
    //                 updatedAt: null,
    //                 pname: null,
    //                 list: null
    //             },
    //             {
    //                 menuId: 40,
    //                 parentId: 36,
    //                 name: "门牌管理",
    //                 url: "modules/pro/door",
    //                 permit: "building:doorplates:page",
    //                 type: 3,
    //                 icon: "zonghe",
    //                 oindex: 2,
    //                 createdBy: null,
    //                 updatedBy: null,
    //                 createdAt: null,
    //                 updatedAt: null,
    //                 pname: null,
    //                 list: null
    //             }
    //         ]
    //     },
    //     {
    //         menuId: 42,
    //         parentId: 1,
    //         name: "企业运营",
    //         url: "",
    //         permit: "",
    //         type: 2,
    //         icon: "yunyingzhongxin",
    //         oindex: 88,
    //         createdBy: null,
    //         updatedBy: null,
    //         createdAt: null,
    //         updatedAt: null,
    //         pname: null,
    //         list: [
    //             {
    //                 menuId: 50,
    //                 parentId: 42,
    //                 name: "授权管理",
    //                 url: "modules/ope/author",
    //                 permit: "user:users:page",
    //                 type: 3,
    //                 icon: "zonghe",
    //                 oindex: 3,
    //                 createdBy: null,
    //                 updatedBy: null,
    //                 createdAt: null,
    //                 updatedAt: null,
    //                 pname: null,
    //                 list: null
    //             },
    //             {
    //                 menuId: 49,
    //                 parentId: 42,
    //                 name: "用户管理",
    //                 url: "modules/ope/user",
    //                 permit: "user:users:page",
    //                 type: 3,
    //                 icon: "zonghe",
    //                 oindex: 2,
    //                 createdBy: null,
    //                 updatedBy: null,
    //                 createdAt: null,
    //                 updatedAt: null,
    //                 pname: null,
    //                 list: null
    //             },
    //             {
    //                 menuId: 48,
    //                 parentId: 42,
    //                 name: "企业管理",
    //                 url: "modules/ope/company",
    //                 permit: "user:companys:page",
    //                 type: 3,
    //                 icon: "zonghe",
    //                 oindex: 1,
    //                 createdBy: null,
    //                 updatedBy: null,
    //                 createdAt: null,
    //                 updatedAt: null,
    //                 pname: null,
    //                 list: null
    //             }
    //         ]
    //     },
    //     {
    //         menuId: 295,
    //         parentId: 1,
    //         name: "能耗管理",
    //         url: "",
    //         permit: "",
    //         type: 2,
    //         icon: "zhedie",
    //         oindex: 83,
    //         createdBy: null,
    //         updatedBy: null,
    //         createdAt: null,
    //         updatedAt: null,
    //         pname: null,
    //         list: [
    //             {
    //                 menuId: 296,
    //                 parentId: 295,
    //                 name: "电表数据",
    //                 url: "modules/SuperTube/EnergyManagement/electric",
    //                 permit:
    //                     "pm:devices:getDevices,pm:devices:records:getRecords,pm:devices:records:deleteRecord,pm:devices:records:exportRecords",
    //                 type: 3,
    //                 icon: "zonghe",
    //                 oindex: 6,
    //                 createdBy: null,
    //                 updatedBy: null,
    //                 createdAt: null,
    //                 updatedAt: null,
    //                 pname: null,
    //                 list: null
    //             },
    //             {
    //                 menuId: 297,
    //                 parentId: 295,
    //                 name: "水表数据",
    //                 url: "modules/SuperTube/EnergyManagement/water",
    //                 permit:
    //                     "pm:devices:getDevices,pm:devices:records:getRecords,pm:devices:records:exportRecords",
    //                 type: 3,
    //                 icon: "zonghe",
    //                 oindex: 3,
    //                 createdBy: null,
    //                 updatedBy: null,
    //                 createdAt: null,
    //                 updatedAt: null,
    //                 pname: null,
    //                 list: null
    //             },
    //             {
    //                 menuId: 298,
    //                 parentId: 295,
    //                 name: "燃气数据",
    //                 url: "modules/SuperTube/EnergyManagement/gas",
    //                 permit:
    //                     "pm:devices:getDevices,pm:devices:records:getRecords,pm:devices:records:exportRecords",
    //                 type: 3,
    //                 icon: "zonghe",
    //                 oindex: 1,
    //                 createdBy: null,
    //                 updatedBy: null,
    //                 createdAt: null,
    //                 updatedAt: null,
    //                 pname: null,
    //                 list: null
    //             }
    //         ]
    //     },
    //     {
    //         menuId: 41,
    //         parentId: 1,
    //         name: "设备管理",
    //         url: "",
    //         permit: "",
    //         type: 2,
    //         icon: "shebei",
    //         oindex: 75,
    //         createdBy: null,
    //         updatedBy: null,
    //         createdAt: null,
    //         updatedAt: null,
    //         pname: null,
    //         list: [
    //             {
    //                 menuId: 47,
    //                 parentId: 41,
    //                 name: "设备分组",
    //                 url: "modules/dev/group",
    //                 permit: "access:groups:page",
    //                 type: 3,
    //                 icon: "zonghe",
    //                 oindex: 2,
    //                 createdBy: null,
    //                 updatedBy: null,
    //                 createdAt: null,
    //                 updatedAt: null,
    //                 pname: null,
    //                 list: null
    //             },
    //             {
    //                 menuId: 46,
    //                 parentId: 41,
    //                 name: "设备管理列表",
    //                 url: "modules/dev/manage",
    //                 permit: "access:devices:page",
    //                 type: 3,
    //                 icon: "zonghe",
    //                 oindex: 0,
    //                 createdBy: null,
    //                 updatedBy: null,
    //                 createdAt: null,
    //                 updatedAt: null,
    //                 pname: null,
    //                 list: null
    //             }
    //         ]
    //     },
    //     {
    //         menuId: 43,
    //         parentId: 1,
    //         name: "企业管理",
    //         url: "",
    //         permit: "",
    //         type: 2,
    //         icon: "qiye",
    //         oindex: 72,
    //         createdBy: null,
    //         updatedBy: null,
    //         createdAt: null,
    //         updatedAt: null,
    //         pname: null,
    //         list: [
    //             {
    //                 menuId: 51,
    //                 parentId: 43,
    //                 name: "用户认证",
    //                 url: "modules/bus/userauth",
    //                 permit: "user:companyUserRel:page",
    //                 type: 3,
    //                 icon: "zonghe",
    //                 oindex: 2,
    //                 createdBy: null,
    //                 updatedBy: null,
    //                 createdAt: null,
    //                 updatedAt: null,
    //                 pname: null,
    //                 list: null
    //             }
    //         ]
    //     },
    //     {
    //         menuId: 35,
    //         parentId: 1,
    //         name: "内容运营",
    //         url: "",
    //         permit: "",
    //         type: 2,
    //         icon: "neirong",
    //         oindex: 71,
    //         createdBy: null,
    //         updatedBy: null,
    //         createdAt: null,
    //         updatedAt: null,
    //         pname: null,
    //         list: [
    //             {
    //                 menuId: 37,
    //                 parentId: 35,
    //                 name: "广告管理",
    //                 url: "modules/adv/advmanage",
    //                 permit: "mkt:advertisements:page",
    //                 type: 3,
    //                 icon: "zonghe",
    //                 oindex: 10,
    //                 createdBy: null,
    //                 updatedBy: null,
    //                 createdAt: null,
    //                 updatedAt: null,
    //                 pname: null,
    //                 list: null
    //             },
    //             {
    //                 menuId: 290,
    //                 parentId: 35,
    //                 name: "活动管理",
    //                 url: "modules/adv/activityList",
    //                 permit:
    //                     "act:infos:getActivities,act:infos:addActivity,act:infos:getActivityDetail,act:interactive:getInteractives,act:infos:topActivity,act:infos:deleteActivity,act:interactive:deleteInteractive,act:infos:updateActivity,act:interactive:addInteractive",
    //                 type: 3,
    //                 icon: "zonghe",
    //                 oindex: 8,
    //                 createdBy: null,
    //                 updatedBy: null,
    //                 createdAt: null,
    //                 updatedAt: null,
    //                 pname: null,
    //                 list: null
    //             },
    //             {
    //                 menuId: 299,
    //                 parentId: 35,
    //                 name: "消息推送",
    //                 url: "modules/adv/MessagePush",
    //                 permit:
    //                     "note:messages:getMessages,note:messages:addMessage,note:messages:getPhones,note:messages:uploadPhones",
    //                 type: 3,
    //                 icon: "zonghe",
    //                 oindex: 6,
    //                 createdBy: null,
    //                 updatedBy: null,
    //                 createdAt: null,
    //                 updatedAt: null,
    //                 pname: null,
    //                 list: null
    //             },
    //             {
    //                 menuId: 150,
    //                 parentId: 35,
    //                 name: "资讯管理",
    //                 url: "modules/adv/infomation",
    //                 permit: "info:discoveries:getDiscoveriesV2",
    //                 type: 3,
    //                 icon: "zonghe",
    //                 oindex: 3,
    //                 createdBy: null,
    //                 updatedBy: null,
    //                 createdAt: null,
    //                 updatedAt: null,
    //                 pname: null,
    //                 list: null
    //             },
    //             {
    //                 menuId: 131,
    //                 parentId: 35,
    //                 name: "公告管理",
    //                 url: "modules/adv/notice",
    //                 permit: "notice:announcement:addAnnouncement",
    //                 type: 3,
    //                 icon: "zonghe",
    //                 oindex: 2,
    //                 createdBy: null,
    //                 updatedBy: null,
    //                 createdAt: null,
    //                 updatedAt: null,
    //                 pname: null,
    //                 list: null
    //             },
    //             {
    //                 menuId: 202,
    //                 parentId: 35,
    //                 name: "企业联盟",
    //                 url: "modules/adv/service",
    //                 permit: "union:services:getServices",
    //                 type: 3,
    //                 icon: "zonghe",
    //                 oindex: 1,
    //                 createdBy: null,
    //                 updatedBy: null,
    //                 createdAt: null,
    //                 updatedAt: null,
    //                 pname: null,
    //                 list: null
    //             },
    //             {
    //                 menuId: 187,
    //                 parentId: 35,
    //                 name: "意见反馈管理",
    //                 url: "modules/adv/feedback",
    //                 permit: "info:feedback:getFeedbackList",
    //                 type: 3,
    //                 icon: "zonghe",
    //                 oindex: 0,
    //                 createdBy: null,
    //                 updatedBy: null,
    //                 createdAt: null,
    //                 updatedAt: null,
    //                 pname: null,
    //                 list: null
    //             }
    //         ]
    //     },
    //     {
    //         menuId: 270,
    //         parentId: 1,
    //         name: "人脸管理",
    //         url: "",
    //         permit: "",
    //         type: 2,
    //         icon: "zhedie",
    //         oindex: 68,
    //         createdBy: null,
    //         updatedBy: null,
    //         createdAt: null,
    //         updatedAt: null,
    //         pname: null,
    //         list: [
    //             {
    //                 menuId: 271,
    //                 parentId: 270,
    //                 name: "人员列表",
    //                 url: "modules/faceDevice/personList",
    //                 permit: "",
    //                 type: 3,
    //                 icon: "zonghe",
    //                 oindex: 10,
    //                 createdBy: null,
    //                 updatedBy: null,
    //                 createdAt: null,
    //                 updatedAt: null,
    //                 pname: null,
    //                 list: null
    //             },
    //             {
    //                 menuId: 291,
    //                 parentId: 270,
    //                 name: "设备分组",
    //                 url: "modules/faceDevice/group",
    //                 permit: "",
    //                 type: 3,
    //                 icon: "menu",
    //                 oindex: 0,
    //                 createdBy: null,
    //                 updatedBy: null,
    //                 createdAt: null,
    //                 updatedAt: null,
    //                 pname: null,
    //                 list: null
    //             },
    //             {
    //                 menuId: 272,
    //                 parentId: 270,
    //                 name: "设备列表",
    //                 url: "modules/faceDevice/faceDeviceList",
    //                 permit: "",
    //                 type: 3,
    //                 icon: "zonghe",
    //                 oindex: 0,
    //                 createdBy: null,
    //                 updatedBy: null,
    //                 createdAt: null,
    //                 updatedAt: null,
    //                 pname: null,
    //                 list: null
    //             },
    //             {
    //                 menuId: 293,
    //                 parentId: 270,
    //                 name: "访客信息列表",
    //                 url: "modules/faceDevice/visitorUser",
    //                 permit: "",
    //                 type: 3,
    //                 icon: "role",
    //                 oindex: 0,
    //                 createdBy: null,
    //                 updatedBy: null,
    //                 createdAt: null,
    //                 updatedAt: null,
    //                 pname: null,
    //                 list: null
    //             },
    //             {
    //                 menuId: 294,
    //                 parentId: 270,
    //                 name: "黑名单管理",
    //                 url: "modules/faceDevice/blacklist",
    //                 permit: "",
    //                 type: 3,
    //                 icon: "suoding",
    //                 oindex: 0,
    //                 createdBy: null,
    //                 updatedBy: null,
    //                 createdAt: null,
    //                 updatedAt: null,
    //                 pname: null,
    //                 list: null
    //             },
    //             {
    //                 menuId: 292,
    //                 parentId: 270,
    //                 name: "识别记录",
    //                 url: "modules/faceDevice/discernRecord",
    //                 permit: "",
    //                 type: 3,
    //                 icon: "role",
    //                 oindex: 0,
    //                 createdBy: null,
    //                 updatedBy: null,
    //                 createdAt: null,
    //                 updatedAt: null,
    //                 pname: null,
    //                 list: null
    //             }
    //         ]
    //     },
    //     {
    //         menuId: 273,
    //         parentId: 1,
    //         name: "智能开关",
    //         url: "",
    //         permit: "",
    //         type: 2,
    //         icon: "zhedie",
    //         oindex: 67,
    //         createdBy: null,
    //         updatedBy: null,
    //         createdAt: null,
    //         updatedAt: null,
    //         pname: null,
    //         list: [
    //             {
    //                 menuId: 274,
    //                 parentId: 273,
    //                 name: "设备列表",
    //                 url: "modules/intelligentSwitch/inteDevicelist",
    //                 permit: "dvc:switchDevices:update",
    //                 type: 3,
    //                 icon: "zonghe",
    //                 oindex: 10,
    //                 createdBy: null,
    //                 updatedBy: null,
    //                 createdAt: null,
    //                 updatedAt: null,
    //                 pname: null,
    //                 list: null
    //             }
    //         ]
    //     },
    //     {
    //         menuId: 145,
    //         parentId: 1,
    //         name: "会议室预订",
    //         url: "",
    //         permit: "",
    //         type: 2,
    //         icon: "huiyishi",
    //         oindex: 65,
    //         createdBy: null,
    //         updatedBy: null,
    //         createdAt: null,
    //         updatedAt: null,
    //         pname: null,
    //         list: [
    //             {
    //                 menuId: 146,
    //                 parentId: 145,
    //                 name: "会议室列表",
    //                 url: "modules/room/roomList",
    //                 permit:
    //                     "meeting:room:getRoomList,meeting:room:saveRoom,meeting:room:updateRoom,meeting:room:deleteRoom",
    //                 type: 3,
    //                 icon: "zonghe",
    //                 oindex: 2,
    //                 createdBy: null,
    //                 updatedBy: null,
    //                 createdAt: null,
    //                 updatedAt: null,
    //                 pname: null,
    //                 list: null
    //             },
    //             {
    //                 menuId: 147,
    //                 parentId: 145,
    //                 name: "预约订单",
    //                 url: "modules/room/roomOrder",
    //                 permit:
    //                     "meeting:order:getOrderList,meeting:order:orderRefund,meeting:order:exportOrders",
    //                 type: 3,
    //                 icon: "zonghe",
    //                 oindex: 1,
    //                 createdBy: null,
    //                 updatedBy: null,
    //                 createdAt: null,
    //                 updatedAt: null,
    //                 pname: null,
    //                 list: null
    //             }
    //         ]
    //     },
    //     {
    //         menuId: 171,
    //         parentId: 1,
    //         name: "相册管理",
    //         url: "",
    //         permit: "",
    //         type: 2,
    //         icon: "xiangce",
    //         oindex: 63,
    //         createdBy: null,
    //         updatedBy: null,
    //         createdAt: null,
    //         updatedAt: null,
    //         pname: null,
    //         list: [
    //             {
    //                 menuId: 172,
    //                 parentId: 171,
    //                 name: "相册列表",
    //                 url: "modules/photo/gallery",
    //                 permit: "info:galleries:getGalleries",
    //                 type: 3,
    //                 icon: "zonghe",
    //                 oindex: 2,
    //                 createdBy: null,
    //                 updatedBy: null,
    //                 createdAt: null,
    //                 updatedAt: null,
    //                 pname: null,
    //                 list: null
    //             },
    //             {
    //                 menuId: 173,
    //                 parentId: 171,
    //                 name: "相片列表",
    //                 url: "modules/photo/photos",
    //                 permit: "info:photos:getPhotos",
    //                 type: 3,
    //                 icon: "zonghe",
    //                 oindex: 1,
    //                 createdBy: null,
    //                 updatedBy: null,
    //                 createdAt: null,
    //                 updatedAt: null,
    //                 pname: null,
    //                 list: null
    //             }
    //         ]
    //     },
    //     {
    //         menuId: 140,
    //         parentId: 1,
    //         name: "基础运营",
    //         url: "",
    //         permit: "",
    //         type: 2,
    //         icon: "baseservice",
    //         oindex: 60,
    //         createdBy: null,
    //         updatedBy: null,
    //         createdAt: null,
    //         updatedAt: null,
    //         pname: null,
    //         list: [
    //             {
    //                 menuId: 141,
    //                 parentId: 140,
    //                 name: "停车缴费",
    //                 url: "modules/base/park",
    //                 permit: "park:carOrders:page,park:carOrders:exportPage",
    //                 type: 3,
    //                 icon: "zonghe",
    //                 oindex: 1,
    //                 createdBy: null,
    //                 updatedBy: null,
    //                 createdAt: null,
    //                 updatedAt: null,
    //                 pname: null,
    //                 list: null
    //             }
    //         ]
    //     },
    //     {
    //         menuId: 183,
    //         parentId: 1,
    //         name: "快递服务",
    //         url: "",
    //         permit: "",
    //         type: 2,
    //         icon: "shoucang",
    //         oindex: 53,
    //         createdBy: null,
    //         updatedBy: null,
    //         createdAt: null,
    //         updatedAt: null,
    //         pname: null,
    //         list: [
    //             {
    //                 menuId: 184,
    //                 parentId: 183,
    //                 name: "订单列表",
    //                 url: "modules/express/oderlist",
    //                 permit:
    //                     "express:orders:getOrders,express:companies:getOptions",
    //                 type: 3,
    //                 icon: "zonghe",
    //                 oindex: 5,
    //                 createdBy: null,
    //                 updatedBy: null,
    //                 createdAt: null,
    //                 updatedAt: null,
    //                 pname: null,
    //                 list: null
    //             },
    //             {
    //                 menuId: 287,
    //                 parentId: 183,
    //                 name: "派件数据统计",
    //                 url: "modules/express/pieOrderChart",
    //                 permit:
    //                     "express:statistics:getDispatchCompanies,express:statistics:getDispatchNum,express:statistics:getDispatchNumRank",
    //                 type: 3,
    //                 icon: "zonghe",
    //                 oindex: 2,
    //                 createdBy: null,
    //                 updatedBy: null,
    //                 createdAt: null,
    //                 updatedAt: null,
    //                 pname: null,
    //                 list: null
    //             },
    //             {
    //                 menuId: 288,
    //                 parentId: 183,
    //                 name: "寄件数据统计",
    //                 url: "modules/express/mailOrderChart",
    //                 permit:
    //                     "express:companies:getOptions,express:orders:getExpressOrderNum,express:orders:getExpressRevenue",
    //                 type: 3,
    //                 icon: "zonghe",
    //                 oindex: 1,
    //                 createdBy: null,
    //                 updatedBy: null,
    //                 createdAt: null,
    //                 updatedAt: null,
    //                 pname: null,
    //                 list: null
    //             }
    //         ]
    //     },
    //     {
    //         menuId: 148,
    //         parentId: 1,
    //         name: "数据墙",
    //         url: "",
    //         permit: "",
    //         type: 2,
    //         icon: "shuju",
    //         oindex: 45,
    //         createdBy: null,
    //         updatedBy: null,
    //         createdAt: null,
    //         updatedAt: null,
    //         pname: null,
    //         list: [
    //             {
    //                 menuId: 149,
    //                 parentId: 148,
    //                 name: "平台数据",
    //                 url: "modules/data/datawall",
    //                 permit:
    //                     "statistics:platform:KeyDatas,statistics:app:KeyDatas",
    //                 type: 3,
    //                 icon: "zonghe",
    //                 oindex: 1,
    //                 createdBy: null,
    //                 updatedBy: null,
    //                 createdAt: null,
    //                 updatedAt: null,
    //                 pname: null,
    //                 list: null
    //             }
    //         ]
    //     },
    //     {
    //         menuId: 188,
    //         parentId: 1,
    //         name: "访客管理",
    //         url: "",
    //         permit: "",
    //         type: 2,
    //         icon: "fangke",
    //         oindex: 30,
    //         createdBy: null,
    //         updatedBy: null,
    //         createdAt: null,
    //         updatedAt: null,
    //         pname: null,
    //         list: [
    //             {
    //                 menuId: 193,
    //                 parentId: 188,
    //                 name: "广告管理",
    //                 url: "modules/vistor/advlist",
    //                 permit: "visitor:advertisements:page",
    //                 type: 3,
    //                 icon: "zonghe",
    //                 oindex: 8,
    //                 createdBy: null,
    //                 updatedBy: null,
    //                 createdAt: null,
    //                 updatedAt: null,
    //                 pname: null,
    //                 list: null
    //             }
    //         ]
    //     },
    //     {
    //         menuId: 341,
    //         parentId: 1,
    //         name: "驻地网",
    //         url: "",
    //         permit: "",
    //         type: 2,
    //         icon: "yunyingzhongxin",
    //         oindex: 20,
    //         createdBy: null,
    //         updatedBy: null,
    //         createdAt: null,
    //         updatedAt: null,
    //         pname: null,
    //         list: [
    //             {
    //                 menuId: 342,
    //                 parentId: 341,
    //                 name: "机房管理",
    //                 url: "modules/residentNetwork/lablist",
    //                 permit:
    //                     "cpn:labs:getLabs,cpn:labs:addLab,cpn:labs:deleteLab",
    //                 type: 3,
    //                 icon: "zonghe",
    //                 oindex: 10,
    //                 createdBy: null,
    //                 updatedBy: null,
    //                 createdAt: null,
    //                 updatedAt: null,
    //                 pname: null,
    //                 list: null
    //             },
    //             {
    //                 menuId: 343,
    //                 parentId: 341,
    //                 name: "ODF管理",
    //                 url: "modules/residentNetwork/odflist",
    //                 permit:
    //                     "cpn:odfs:getOdfs,cpn:odfs:addOdf,cpn:odfs:updateOdf,cpn:odfs:deleteOdf,cpn:cables:getOptions,cpn:cables:segments:getOptions,cpn:odfs:terminals:getTerminals",
    //                 type: 3,
    //                 icon: "zonghe",
    //                 oindex: 8,
    //                 createdBy: null,
    //                 updatedBy: null,
    //                 createdAt: null,
    //                 updatedAt: null,
    //                 pname: null,
    //                 list: null
    //             },
    //             {
    //                 menuId: 344,
    //                 parentId: 341,
    //                 name: "光缆管理",
    //                 url: "modules/residentNetwork/cableslist",
    //                 permit:
    //                     "cpn:cables:updateCable,cpn:cables:getCables,cpn:cables:deleteCable,cpn:cables:segments:updateSegment,cpn:cables:segments:getSegments,cpn:cables:segments:deleteSegment,cpn:import:importCables,cpn:import:importSegments,cpn:excels:exportExcels",
    //                 type: 3,
    //                 icon: "zonghe",
    //                 oindex: 6,
    //                 createdBy: null,
    //                 updatedBy: null,
    //                 createdAt: null,
    //                 updatedAt: null,
    //                 pname: null,
    //                 list: null
    //             }
    //         ]
    //     },
    //     {
    //         menuId: 13,
    //         parentId: 1,
    //         name: "店铺管理",
    //         url: null,
    //         permit: null,
    //         type: 2,
    //         icon: "dianpu",
    //         oindex: 15,
    //         createdBy: null,
    //         updatedBy: null,
    //         createdAt: null,
    //         updatedAt: null,
    //         pname: null,
    //         list: [
    //             {
    //                 menuId: 14,
    //                 parentId: 13,
    //                 name: "店铺列表",
    //                 url: "modules/sto/stolist",
    //                 permit: "merchant:shops:getShopList",
    //                 type: 3,
    //                 icon: "zonghe",
    //                 oindex: 1,
    //                 createdBy: null,
    //                 updatedBy: null,
    //                 createdAt: null,
    //                 updatedAt: null,
    //                 pname: null,
    //                 list: null
    //             }
    //         ]
    //     },
    //     {
    //         menuId: 20,
    //         parentId: 1,
    //         name: "商品管理",
    //         url: null,
    //         permit: null,
    //         type: 2,
    //         icon: "shangping",
    //         oindex: 14,
    //         createdBy: null,
    //         updatedBy: null,
    //         createdAt: null,
    //         updatedAt: null,
    //         pname: null,
    //         list: [
    //             {
    //                 menuId: 28,
    //                 parentId: 20,
    //                 name: "类目管理",
    //                 url: "modules/goods/category",
    //                 permit: "product:groups:getGroupList",
    //                 type: 3,
    //                 icon: "zonghe",
    //                 oindex: 3,
    //                 createdBy: null,
    //                 updatedBy: null,
    //                 createdAt: null,
    //                 updatedAt: null,
    //                 pname: null,
    //                 list: null
    //             },
    //             {
    //                 menuId: 268,
    //                 parentId: 20,
    //                 name: "运营商品列表",
    //                 url: "modules/goods/operateGoodsList",
    //                 permit:
    //                     "product:goods:getGoodsList,merchant:shops:getShopOptions,product:goods:updateGoods",
    //                 type: 3,
    //                 icon: "zonghe",
    //                 oindex: 1,
    //                 createdBy: null,
    //                 updatedBy: null,
    //                 createdAt: null,
    //                 updatedAt: null,
    //                 pname: null,
    //                 list: null
    //             }
    //         ]
    //     },
    //     {
    //         menuId: 3,
    //         parentId: 1,
    //         name: "分组管理",
    //         url: "",
    //         permit: "",
    //         type: 2,
    //         icon: "fenzu",
    //         oindex: 12,
    //         createdBy: null,
    //         updatedBy: null,
    //         createdAt: null,
    //         updatedAt: null,
    //         pname: null,
    //         list: [
    //             {
    //                 menuId: 9,
    //                 parentId: 3,
    //                 name: "主页推荐分组",
    //                 url: "modules/ind/indlist",
    //                 permit:
    //                     "product:groups:getGroupList,product:groups:getGroupGoods,product:groups:sortGroup,merchant:shops:sortShop",
    //                 type: 3,
    //                 icon: "zonghe",
    //                 oindex: 2,
    //                 createdBy: null,
    //                 updatedBy: null,
    //                 createdAt: null,
    //                 updatedAt: null,
    //                 pname: null,
    //                 list: null
    //             },
    //             {
    //                 menuId: 4,
    //                 parentId: 3,
    //                 name: "首页推荐分组",
    //                 url: "modules/ind/more",
    //                 permit:
    //                     "product:groups:getGroupList,product:groups:getGroupGoods,product:goods:getGoodsDetail",
    //                 type: 3,
    //                 icon: "zonghe",
    //                 oindex: 1,
    //                 createdBy: null,
    //                 updatedBy: null,
    //                 createdAt: null,
    //                 updatedAt: null,
    //                 pname: null,
    //                 list: null
    //             }
    //         ]
    //     },
    //     {
    //         menuId: 142,
    //         parentId: 1,
    //         name: "数据统计",
    //         url: "",
    //         permit: "",
    //         type: 2,
    //         icon: "tongji",
    //         oindex: 11,
    //         createdBy: null,
    //         updatedBy: null,
    //         createdAt: null,
    //         updatedAt: null,
    //         pname: null,
    //         list: [
    //             {
    //                 menuId: 144,
    //                 parentId: 142,
    //                 name: "商品统计",
    //                 url: "modules/datacount/goodscount",
    //                 permit:
    //                     "statistics:goods:statisticsSalesAmount,statistics:goods:statisticsGoodsNum",
    //                 type: 3,
    //                 icon: "zonghe",
    //                 oindex: 2,
    //                 createdBy: null,
    //                 updatedBy: null,
    //                 createdAt: null,
    //                 updatedAt: null,
    //                 pname: null,
    //                 list: null
    //             },
    //             {
    //                 menuId: 143,
    //                 parentId: 142,
    //                 name: "订单统计",
    //                 url: "modules/datacount/ordercount",
    //                 permit: "statistics:goods:statisticsOrderNum",
    //                 type: 3,
    //                 icon: "zonghe",
    //                 oindex: 1,
    //                 createdBy: null,
    //                 updatedBy: null,
    //                 createdAt: null,
    //                 updatedAt: null,
    //                 pname: null,
    //                 list: null
    //             }
    //         ]
    //     },
    //     {
    //         menuId: 44,
    //         parentId: 1,
    //         name: "订单管理",
    //         url: null,
    //         permit: null,
    //         type: 2,
    //         icon: "dingdan",
    //         oindex: 9,
    //         createdBy: null,
    //         updatedBy: null,
    //         createdAt: null,
    //         updatedAt: null,
    //         pname: null,
    //         list: [
    //             {
    //                 menuId: 269,
    //                 parentId: 44,
    //                 name: "通达顺订单",
    //                 url: "modules/order/orderList",
    //                 permit:
    //                     "transaction:orders:getOrderList,transaction:orders:getOrderDetails,merchant:shops:getShopOptions,transaction:orders:exportOrdersV1",
    //                 type: 3,
    //                 icon: "zonghe",
    //                 oindex: 2,
    //                 createdBy: null,
    //                 updatedBy: null,
    //                 createdAt: null,
    //                 updatedAt: null,
    //                 pname: null,
    //                 list: null
    //             },
    //             {
    //                 menuId: 45,
    //                 parentId: 44,
    //                 name: "订单列表",
    //                 url: "modules/order/ordermanagement",
    //                 permit:
    //                     "transaction:orders:getOrderList,merchant:shops:getShopOptions,transaction:orders:exportOrdersV2,transaction:orders:exportOrdersV1",
    //                 type: 3,
    //                 icon: "zonghe",
    //                 oindex: 0,
    //                 createdBy: null,
    //                 updatedBy: null,
    //                 createdAt: null,
    //                 updatedAt: null,
    //                 pname: null,
    //                 list: null
    //             }
    //         ]
    //     },
    //     {
    //         menuId: 308,
    //         parentId: 1,
    //         name: "京东购管理",
    //         url: "",
    //         permit: "",
    //         type: 2,
    //         icon: "shangping",
    //         oindex: 6,
    //         createdBy: null,
    //         updatedBy: null,
    //         createdAt: null,
    //         updatedAt: null,
    //         pname: null,
    //         list: [
    //             {
    //                 menuId: 309,
    //                 parentId: 308,
    //                 name: "商品列表",
    //                 url: "modules/Jdgo/Shop/ShopList",
    //                 permit: "",
    //                 type: 3,
    //                 icon: "zonghe",
    //                 oindex: 3,
    //                 createdBy: null,
    //                 updatedBy: null,
    //                 createdAt: null,
    //                 updatedAt: null,
    //                 pname: null,
    //                 list: null
    //             },
    //             {
    //                 menuId: 310,
    //                 parentId: 308,
    //                 name: "专题列表",
    //                 url: "modules/Jdgo/Special/SpecialList",
    //                 permit: "",
    //                 type: 3,
    //                 icon: "zonghe",
    //                 oindex: 2,
    //                 createdBy: null,
    //                 updatedBy: null,
    //                 createdAt: null,
    //                 updatedAt: null,
    //                 pname: null,
    //                 list: null
    //             },
    //             {
    //                 menuId: 311,
    //                 parentId: 308,
    //                 name: "订单列表",
    //                 url: "modules/Jdgo/Order/OrderList",
    //                 permit: "",
    //                 type: 3,
    //                 icon: "zonghe",
    //                 oindex: 1,
    //                 createdBy: null,
    //                 updatedBy: null,
    //                 createdAt: null,
    //                 updatedAt: null,
    //                 pname: null,
    //                 list: null
    //             },
    //             {
    //                 menuId: 316,
    //                 parentId: 308,
    //                 name: "广告列表",
    //                 url: "modules/Jdgo/Adv/AdvList",
    //                 permit: "",
    //                 type: 3,
    //                 icon: "zonghe",
    //                 oindex: 0,
    //                 createdBy: null,
    //                 updatedBy: null,
    //                 createdAt: null,
    //                 updatedAt: null,
    //                 pname: null,
    //                 list: null
    //             }
    //         ]
    //     }
    // ],
    ,
    permissions: [
            "visitor:advertisements:page",
            "user:users:page",
            "transaction:orders:getOrderList",
            "access:groups:page",
            "cpn:cables:deleteCable",
            "meeting:room:updateRoom",
            "user:companys:noCompanyAdmin",
            "info:discoveries:sortDiscovery",
            "product:groups:addGroup",
            "meeting:room:getRoomList",
            "building:doorplates:getById",
            "notice:announcement:updateAnnouncement",
            "pm:devices:records:exportRecords",
            "user:users:update",
            "access:groups:save",
            "access:devices:delete",
            "building:buildings:update",
            "merchant:shops:sortShop",
            "cpn:cables:updateCable",
            "user:users:userDeviceGroup",
            "cpn:import:importTerminals",
            "merchant:shops:addShop",
            "cpn:labs:getLabs",
            "merchant:shops:deleteShop",
            "user:companys:noCompanyGroup",
            "mkt:advertisements:getById",
            "act:infos:getActivityDetail",
            "building:doorplates:delete",
            "info:discoveries:getDiscoveriesV2",
            "union:services:deleteService",
            "product:groups:sortGroupGoods",
            "user:companys:getById",
            "express:orders:getDetails",
            "notice:announcement:deleteAnnouncement",
            "cpn:labs:addLab",
            "access:devices:getById",
            "act:interactive:addInteractive",
            "meeting:room:deleteRoom",
            "cpn:excels:exportExcels",
            "cpn:import:importCables",
            "product:groups:bindGroupGoods",
            "info:discoveries:deleteDiscovery",
            "express:statistics:getDispatchNumRank",
            "note:messages:getPhones",
            "express:statistics:getDispatchNum",
            "dvc:switchDevices:update",
            "product:groups:getGroupGoods",
            "notice:announcement:getAnnouncementDetails",
            "act:infos:topActivity",
            "user:companys:companyGroup",
            "express:orders:exportOrders",
            "access:groups:delete",
            "meeting:room:saveRoom",
            "meeting:order:getOrderList",
            "park:carOrders:exportPage",
            "merchant:shops:getShopDetails",
            "statistics:platform:KeyDatas",
            "user:companys:page",
            "product:goods:getGoodsDetail",
            "access:devices:page",
            "info:galleries:addGallery",
            "user:companys:bundlingAdmin",
            "access:groups:update",
            "notice:announcement:getAnnouncements",
            "transaction:orders:exportOrdersV1",
            "transaction:orders:exportOrdersV2",
            "user:companys:update",
            "cpn:odfs:deleteOdf",
            "product:goods:updateGoods",
            "cpn:cables:segments:updateSegment",
            "union:services:getServices",
            "info:feedback:getFeedbackList",
            "building:floors:update",
            "building:floors:page",
            "access:devices:save",
            "act:infos:addActivity",
            "user:users:save",
            "cpn:odfs:terminals:getTerminals",
            "building:doorplates:update",
            "product:goods:getGoodsList",
            "info:discoveries:addDiscovery",
            "merchant:shops:updateShop",
            "access:groups:getById",
            "note:messages:uploadPhones",
            "cpn:terminals:business:stopBusiness",
            "info:discoveries:getDiscoveryDetailsV2",
            "user:companys:bundlingDeviceGroup",
            "info:discoveries:comments:deleteComment",
            "pm:devices:getDevices",
            "pm:devices:records:getRecords",
            "note:messages:addMessage",
            "express:orders:getExpressRevenue",
            "union:services:sortService",
            "cpn:cables:segments:getSegments",
            "access:groups:devices",
            "express:companies:getOptions",
            "park:carOrders:page",
            "building:buildings:save",
            "building:doorplates:page",
            "info:photos:deletePhoto",
            "product:groups:unbindGroupGoods",
            "building:doorplates:save",
            "user:companys:companyAdmin",
            "cpn:cables:getOptions",
            "building:buildings:delete",
            "building:buildings:getById",
            "info:discoveries:comments:getComments",
            "merchant:shops:getShopOptions",
            "pm:devices:records:deleteRecord",
            "access:groups:bundlingDevice",
            "cpn:odfs:addOdf",
            "access:devices:update",
            "merchant:shops:getShopList",
            "product:groups:updateGroup",
            "user:companys:save",
            "notice:announcement:addAnnouncement",
            "access:groups:unBundlingDevice",
            "info:discoveries:comments:replies:deleteReply",
            "union:services:getServiceInfo",
            "mkt:advertisements:settop",
            "express:orders:getExpressOrderNum",
            "user:companyUserRel:page",
            "user:users:noUserDeviceGroup",
            "cpn:odfs:getOdfs",
            "user:users:unBundlingGroup",
            "info:discoveries:comments:replies:addReply",
            "cpn:labs:deleteLab",
            "product:groups:getGroupList",
            "user:companys:unBundlingDeviceGroup",
            "express:statistics:getDispatchCompanies",
            "user:companys:unBundlingAdmin",
            "act:interactive:getInteractives",
            "cpn:terminals:business:getBusiness",
            "building:buildings:page",
            "act:infos:updateActivity",
            "mkt:advertisements:page",
            "mkt:advertisements:update",
            "cpn:import:importSegments",
            "mkt:advertisements:delete",
            "union:services:addService",
            "union:services:updateService",
            "info:galleries:getGalleries",
            "transaction:orders:getOrderDetails",
            "user:users:bundlingGroup",
            "info:galleries:updateGallery",
            "express:orders:getOrders",
            "cpn:cables:segments:deleteSegment",
            "cpn:terminals:business:addBusiness",
            "meeting:order:exportOrders",
            "act:infos:deleteActivity",
            "access:groups:noDevices",
            "mkt:advertisements:save",
            "note:messages:getMessages",
            "statistics:goods:statisticsGoodsNum",
            "act:infos:getActivities",
            "info:galleries:deleteGallery",
            "statistics:goods:statisticsOrderNum",
            "info:photos:getPhotos",
            "info:galleries:photos:addPhoto",
            "auth:userMenus:userMenu",
            "cpn:cables:getCables",
            "user:companys:delete",
            "product:groups:deleteGroup",
            "cpn:cables:segments:getOptions",
            "product:groups:sortGroup",
            "cpn:odfs:updateOdf",
            "act:interactive:deleteInteractive",
            "statistics:app:KeyDatas",
            "meeting:order:orderRefund",
            "statistics:goods:statisticsSalesAmount"
        ]
};



export { routeConfig };